queue_rules:
  - name: dep-update
    batch_size: 10
    batch_max_wait_time: 30 min
    queue_conditions:
      - author = renovate[bot]
pull_request_rules:
  - name: Automatically merge Renovate PRs
    conditions:
      - author = renovate[bot]
    actions:
      merge: 
