on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

  publish-github-pkg:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: release-please
    if: needs.release-please.outputs.releases_created
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@iamelevich'

      - name: Setup PNPM and install deps
        uses: ./.github/actions/deps-action
        with:
          node-version: 20

      - name: Build project
        run: pnpm build

      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: release-please
    if: needs.release-please.outputs.releases_created
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to NPM
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM and install deps
        uses: ./.github/actions/deps-action
        with:
          node-version: 20

      - name: Build project
        run: pnpm build

      - run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
