name: Lint and Test
on: [pull_request, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        version: [14, 16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        uses: ./.github/actions/setup-with-deps-action
        with:
          node-version: ${{ matrix.version }}

      - name: Test and Coverage
        run: pnpm run test

  coverage:
    runs-on: ubuntu-latest
    needs: test
    name: Coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        uses: ./.github/actions/setup-with-deps-action
        with:
          node-version: 18

      - name: Lint
        run: pnpm test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        uses: ./.github/actions/setup-with-deps-action
        with:
          node-version: 18

      - name: Lint
        run: pnpm run lint
