name: Lint and Test
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '*.md'
      - 'docs/**'
jobs:
  test:
    strategy:
      matrix:
        node-version: [16, 18, 20, 22]
    runs-on: ubuntu-latest
    name: Test Node.js ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js, PNPM and install deps
        uses: ./.github/actions/setup-with-deps-action
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test and Coverage
        run: pnpm test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          name: ${{ matrix.node-version }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .
